(function(g){var window=this;'use strict';var QY=function(L){L.publish("cardstatechange",L.MB()&&L.Jx()?1:0)},jO=function(L,W){var f=g.fQ(W),I=f?W:arguments;
for(f=f?0:1;f<I.length;f++){if(L==null)return;L=L[I[f]]}return L},h1c=function(L){var W=g.ld(L);
L=g.Wb(L);return new g.py(W.x,W.y,L.width,L.height)},EJC=function(L,W,f){var I=I===void 0?{}:I;
var U;return U=g.MT(L,W,function(){g.n3(U);f.apply(L,arguments)},I)},J3=function(L){L=g.eL(L);
delete t3[L];g.vc(t3)&&PO&&PO.stop()},vJn=function(){PO||(PO=new g.sn(function(){dIc()},20));
var L=PO;L.isActive()||L.start()},dIc=function(){var L=g.dt();
g.lc(t3,function(W){rUc(W,L)});
g.vc(t3)||vJn()},YL=function(L,W,f,I){g.oA.call(this);
if(!Array.isArray(L)||!Array.isArray(W))throw Error("Start and end parameters must be arrays");if(L.length!=W.length)throw Error("Start and end points must be the same length");this.K=L;this.V=W;this.duration=f;this.G=I;this.coords=[];this.progress=this.J=0;this.T=null},rUc=function(L,W){W<L.startTime&&(L.endTime=W+L.endTime-L.startTime,L.startTime=W);
L.progress=(W-L.startTime)/(L.endTime-L.startTime);L.progress>1&&(L.progress=1);L.J=1E3/(W-L.T);L.T=W;BPc(L,L.progress);L.progress==1?(L.W=0,J3(L),L.onFinish(),L.lc()):L.isPlaying()&&L.Bh()},BPc=function(L,W){typeof L.G==="function"&&(W=L.G(W));
L.coords=Array(L.K.length);for(var f=0;f<L.K.length;f++)L.coords[f]=(L.V[f]-L.K[f])*W+L.K[f]},AU5=function(L,W){g.s0.call(this,L);
this.coords=W.coords;this.x=W.coords[0];this.y=W.coords[1];this.z=W.coords[2];this.duration=W.duration;this.progress=W.progress;this.fps=W.J;this.state=W.W},FX=function(L,W,f,I,U){YL.call(this,W,f,I,U);
this.element=L},SRQ=function(L,W,f,I,U){if(W.length!=2||f.length!=2)throw Error("Start and end points must be 2D");
FX.call(this,L,W,f,I,U)},Zrc=function(L){return Math.pow(L,3)},DID=function(L){return 3*L*L-2*L*L*L},w4t=function(L){g.a.call(this);
this.K=L||window;this.W=[]},aN=function(L){return L.baseUrl||null},C6=function(L,W){return g.TX(g.D4(L,W),function(f){return!!f})},z1Q=function(L,W,f){function I(Ey){var IR=Ey.hovercardButton;
if(!IR)return null;IR=IR.subscribeButtonRenderer;if(!IR)return null;var rF=e(IR.unsubscribedButtonText),$r=e(IR.subscribedButtonText);if(IR.subscribed){var gF=e(IR.subscriberCountWithUnsubscribeText);var xr=e(IR.subscriberCountText)}else gF=e(IR.subscriberCountText),xr=e(IR.subscriberCountWithSubscribeText);var vA=null;if(Ey.signinEndpoint){vA=jO(Ey,"signinEndpoint","webNavigationEndpointData","url");if(!vA){var Ei,qz;vA=(qz=g.R((Ei=IR.signInEndpoint)==null?void 0:Ei.commandMetadata,g.Xw))==null?
void 0:qz.url}if(!vA)return null}return rF&&($r||vA)?{subscribed:IR.subscribed,subscribeText:rF,subscribeCount:gF,unsubscribeText:$r,unsubscribeCount:xr,enabled:IR.enabled,signinUrl:vA,classic:Ey.useClassicSubscribeButton}:null}
function U(Ey){if(Ey){var IR=[],rF=Ey.videoId;rF&&IR.push("v="+rF);(rF=Ey.playlistId)&&IR.push("list="+rF);(Ey=Ey.startTimeSeconds)&&IR.push("t="+Ey);return"/watch?"+IR.join("&")}}
function e(Ey){if(!Ey)return null;var IR=Ey.simpleText;return IR?IR:Ey.runs?g.D4(Ey.runs,function(rF){return rF.text}).join(""):null}
W=W.endscreenElementRenderer;if(!W)return null;var b=W.style,E=W.endpoint||{},d=null,v=null,r=!1,B=null,A=null,S=null,Z=null,M=!1,m=null,T=null,K=null,P=null,F=null,p=null;if(b==="VIDEO")g.R(E,g.P2)?d=g.R(E,g.P2).url:(p=g.R(E,g.VZ),d=U(p)),v=!1,B=L,W.thumbnailOverlays?(r=W.thumbnailOverlays[0].thumbnailOverlayTimeStatusRenderer,A=e(r.text),r=r.style==="LIVE"):A=e(W.videoDuration);else if(b==="PLAYLIST")g.R(E,g.P2)?d=g.R(E,g.P2).url:(p=g.R(E,g.VZ),d=U(p)),v=!1,B=L,S=e(W.playlistLength);else if(b===
"CHANNEL"){if(M=jO(E,"browseEndpoint","browseId"))Z=M,d="/channel/"+Z;v=!1;B="new";(M=!!W.isSubscribe)?m=I(W):T=e(W.subscribersText)}else b==="WEBSITE"?((K=jO(E,"urlEndpoint","url"))&&(d=K),v=!0,B="new",K=W.icon.thumbnails[0].url):b==="CREATOR_MERCHANDISE"&&(W.productPrice&&(P=e(W.productPrice)),W.additionalFeesText&&(F=e(W.additionalFeesText)),(v=jO(E,"urlEndpoint","url"))&&(d=v),v=!0,B="new");L=jO(W,"title","accessibility","accessibilityData","label");var H=W.endpoint?W.endpoint.clickTrackingParams:
null,q="";if(W.metadata){var hj=e(W.metadata);hj&&(q=hj)}return{id:"element-"+f,type:b,title:e(W.title),metadata:q,callToAction:e(W.callToAction),E4:W.image,iconUrl:K,left:Number(W.left),width:Number(W.width),top:Number(W.top),aspectRatio:Number(W.aspectRatio),startMs:Math.floor(Number(W.startMs)),endMs:Math.floor(Number(W.endMs)),videoDuration:A,Og:r,playlistLength:S,channelId:Z,subscribeButton:m,subscribersText:T,isSubscribe:M,targetUrl:d||null,wdU:v,sessionData:H?{itct:H}:null,Wsw:B,F7:L?L:null,
isPlaceholder:W.isPlaceholder,impressionUrls:C6(W.impressionUrls||[],aN),LH:C6(W.hovercardShowUrls||[],aN),clickUrls:C6(E.loggingUrls||[],aN),visualElement:g.Zf(W.trackingParams),productPrice:P,additionalFeesText:F,watchEndpoint:p||null}},MVO=function(L,W){var f={startMs:Math.floor(Number(L.startMs)),
impressionUrls:C6(L.impressionUrls||[],aN),elements:C6(L.elements||[],function(I,U){return z1Q(W,I,U)})};
L.trackingParams&&(f.visualElement=g.Zf(L.trackingParams));return f},nJG=function(L){g.ux.call(this,L);
this.T=this.endscreen=null;this.K={};this.J={};this.G=this.N=null;this.U=[];this.W=null;this.Kl=!0;this.V=0;L=L.B();this.X=g.bP(L)||g.ES(L);this.events=new g.XF(this);g.C(this,this.events);this.events.D(this.player,g.iW("creatorendscreen"),this.onCueRangeEnter);this.events.D(this.player,g.xM("creatorendscreen"),this.onCueRangeExit);this.events.D(this.player,"resize",this.xC);this.events.D(window,"focus",this.mw6);this.load();var W=g.Bq("STYLE");(g.Ur("HEAD")[0]||document.body).appendChild(W);this.addOnDisposeCallback(function(){g.wy(W)});
W.sheet&&(W.sheet.insertRule(".ytp-ce-playlist-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABIAAAASBAMAAACk4JNkAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAIVBMVEVMaXGzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7P///91E4wTAAAACXRSTlMArBbpVOtYrReN+x2FAAAAAWJLR0QKaND0VgAAACFJREFUCNdjYCAWzIQAFBaZ6hgVYLKcJnBWGEyWvYGASwCXtBf7m4i3CQAAAABJRU5ErkJggg==) no-repeat center;background-size:18px;width:18px;height:18px}",0),W.sheet.insertRule(".ytp-ce-size-853 .ytp-ce-playlist-icon, .ytp-ce-size-1280 .ytp-ce-playlist-icon, .ytp-ce-size-1920 .ytp-ce-playlist-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABgAAAAYBAMAAAASWSDLAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJ1BMVEVMaXGzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7P///9RfzIKAAAAC3RSTlMAvDeyLvxYtDK9Ogx4T1QAAAABYktHRAyBs1FjAAAAK0lEQVQY02NgoBjshgO8HJoYwKiAMGAD92YHJM7uMCTO9gaEHs4FlPuZAQC8Fj8x/xHjxwAAAABJRU5ErkJggg==) no-repeat center;background-size:24px;width:24px;height:24px}",
0))},X4A=function(L){return L.player.getVideoData().ly?"current":L.X?"new":"current"},p6=function(L){return L.player.B().playerStyle==="creator-endscreen-editor"},VVO=function(L){var W=L.player.getVideoData(),f=W.videoId;
L.T&&L.T.abort();f={method:"POST",onFinish:function(U){var e=L.T=null;U.status===200&&(U=U.responseText,U.substring(0,3)===")]}"&&(U=U.substring(3),e=JSON.parse(U),e=MVO(e,X4A(L))));RN(L,e)},
urlParams:{v:f},withCredentials:!0};L.X&&(f.urlParams.ptype="embedded");var I=W.vz;I&&(f.postParams={ad_tracking:I});if(W=g.lQK(W))if(W=g.ou(W),W=g.Iu(W))L.T=g.V$(W,f)},RN=function(L,W,f){f=f===void 0?!0:f;
L.player.V2("creatorendscreen");L.N&&(L.N.dispose(),L.N=null,L.G.dispose(),L.G=null);for(var I=g.n(Object.values(L.K)),U=I.next();!U.done;U=I.next())U.value.dispose();L.K={};L.J={};L.U.length>0&&(L.U.forEach(function(E){E.dispose()}),L.U.length=0);
L.W&&(g.IA(L.W,"ytp-ce-element-show"),L.W.setAttribute("aria-hidden","true"));L.V=0;if((L.endscreen=W)&&W.elements){f&&mIv(L);f=[];I=new g.sW(W.startMs,0x7ffffffffffff,{id:"ytp-ce-in-endscreen",namespace:"creatorendscreen"});f.push(I);L.player.B().K||(L.N=new g.G({Y:"div",j:"ytp-ce-shadow"}),g.Ln(L.player,L.N.element,4),L.G=new g.O5(L.N,200));for(I=0;I<W.elements.length;++I){U=W.elements[I];var e=uiW(L,U);if(e){L.K[U.id]=e;L.J[U.id]=U;g.Ln(L.player,e.element,4);var b=new g.sW(U.startMs,U.endMs,{id:"ytp-ce-element-"+
U.id,namespace:"creatorendscreen"});f.push(b);KEO(L,e,U)}else g.yH(new g.NT("buildEndscreenElement null",U))}L.player.AD(f);L.xC()}},mIv=function(L){var W=g.wE(),f=g.z5();
f&&W&&L.endscreen.visualElement&&g.xI(g.RV)(void 0,f,W,L.endscreen.visualElement)},uiW=function(L,W){var f=null;
switch(W.type){case "VIDEO":L={Y:"div",d6:["ytp-ce-element","ytp-ce-video"],L:{tabindex:"0","aria-label":W.F7||"","aria-hidden":"true"},C:[{Y:"div",j:"ytp-ce-element-shadow"},{Y:"div",j:"ytp-ce-covering-image",L:Np(W)},{Y:"div",j:"ytp-ce-covering-shadow-top"},{Y:"a",j:"ytp-ce-covering-overlay",L:{href:Ge(L,W.targetUrl),tabindex:"-1"},C:[{Y:"div",d6:["ytp-ce-video-title","ytp-webkit-ellipsis"],L:{dir:g.vj(W.title||"")},NV:W.title},{Y:"div",j:W.Og?"ytp-ce-live-video-duration":"ytp-ce-video-duration",
NV:W.videoDuration||void 0}]}]};f=new g.G(L);break;case "PLAYLIST":L={Y:"div",d6:["ytp-ce-element","ytp-ce-playlist"],L:{tabindex:"0","aria-label":W.F7||"","aria-hidden":"true"},C:[{Y:"div",j:"ytp-ce-element-shadow"},{Y:"div",j:"ytp-ce-covering-image",L:Np(W)},{Y:"div",j:"ytp-ce-covering-shadow-top"},{Y:"a",j:"ytp-ce-covering-overlay",L:{href:Ge(L,W.targetUrl),tabindex:"-1"},C:[{Y:"div",d6:["ytp-ce-playlist-title","ytp-webkit-ellipsis"],L:{dir:g.vj(W.title||"")},NV:W.title},{Y:"div",j:"ytp-ce-playlist-count",
C:[{Y:"div",j:"ytp-ce-playlist-icon"},{Y:"div",j:"ytp-ce-playlist-count-text",NV:W.playlistLength||void 0}]}]}]};f=new g.G(L);break;case "CHANNEL":f={Y:"div",d6:["ytp-ce-element","ytp-ce-channel",W.isSubscribe?"ytp-ce-channel-this":"ytp-ce-channel-that"],L:{tabindex:"0","aria-label":W.F7||"","aria-hidden":"true"},C:[{Y:"div",j:"ytp-ce-element-shadow"},{Y:"div",j:"ytp-ce-expanding-overlay",C:[{Y:"div",j:"ytp-ce-expanding-overlay-hider"},{Y:"div",j:"ytp-ce-expanding-overlay-background"},{Y:"div",j:"ytp-ce-expanding-overlay-content",
C:[{Y:"div",j:"ytp-ce-expanding-overlay-body",C:[{Y:"div",j:"ytp-ce-expanding-overlay-body-padding",C:[{Y:"a",d6:["ytp-ce-channel-title","ytp-ce-link"],L:{href:Ge(L,W.targetUrl),target:"_blank",tabindex:"-1",dir:g.vj(W.title||"")},NV:W.title},W.subscribeButton?{Y:"div",j:"ytp-ce-subscribe-container",C:[{Y:"div",j:"ytp-ce-channel-subscribe"}]}:"",W.subscribersText?{Y:"div",j:"ytp-ce-channel-subscribers-text",NV:W.subscribersText}:"",W.metadata?{Y:"div",d6:["ytp-ce-channel-metadata","yt-ui-ellipsis",
"yt-ui-ellipsis-3"],NV:W.metadata}:""]}]}]}]},{Y:"div",j:"ytp-ce-expanding-image",L:Np(W)}]};f=new g.G(f);var I=g.om(document,"div","ytp-ce-channel-subscribe",f.element)[0];if(W.subscribeButton&&W.channelId){g.$C(I,"ytp-ce-subscribe-button");if(L.player.B().K){var U=null;var e=W.sessionData.itct}else U="endscreen",e=null;U=new g.eI(W.subscribeButton.subscribeText,W.subscribeButton.subscribeCount,W.subscribeButton.unsubscribeText,W.subscribeButton.unsubscribeCount,!!W.subscribeButton.enabled,!!W.subscribeButton.classic,
W.channelId,!!W.subscribeButton.subscribed,U,e,L.player,!1);I.appendChild(U.element);L.U.push(U)}break;case "WEBSITE":L={Y:"div",d6:["ytp-ce-element","ytp-ce-website"],L:{tabindex:"0","aria-label":W.F7||"","aria-hidden":"true"},C:[{Y:"div",j:"ytp-ce-element-shadow"},{Y:"div",j:"ytp-ce-expanding-overlay",C:[{Y:"div",j:"ytp-ce-expanding-overlay-hider"},{Y:"div",j:"ytp-ce-expanding-overlay-background"},{Y:"div",j:"ytp-ce-expanding-overlay-content",C:[{Y:"div",j:"ytp-ce-expanding-overlay-body",C:[{Y:"div",
j:"ytp-ce-expanding-overlay-body-padding",C:[{Y:"div",j:"ytp-ce-website-title",L:{dir:g.vj(W.title||"")},NV:W.title},{Y:"div",j:"ytp-ce-website-metadata",NV:W.metadata},{Y:"a",d6:["ytp-ce-website-goto","ytp-ce-link"],L:{href:Ge(L,W.targetUrl),target:"_blank",tabindex:"-1"},NV:W.callToAction}]}]}]}]},{Y:"div",j:"ytp-ce-expanding-image",L:Np(W)},{Y:"div",j:"ytp-ce-expanding-icon",L:TPL(W.iconUrl)}]};f=new g.G(L);break;case "CREATOR_MERCHANDISE":f="",W.productPrice&&(f={Y:"div",j:"ytp-ce-merchandise-price-container",
C:[{Y:"div",j:"ytp-ce-merchandise-price",NV:W.productPrice}]},W.additionalFeesText&&f.C.push({Y:"div",j:"ytp-ce-merchandise-additional-fees",NV:W.additionalFeesText})),L={Y:"div",d6:["ytp-ce-element","ytp-ce-merchandise"],L:{tabindex:"0","aria-label":W.F7||"","aria-hidden":"true"},C:[{Y:"div",j:"ytp-ce-element-shadow"},{Y:"div",j:"ytp-ce-expanding-overlay",C:[{Y:"div",j:"ytp-ce-expanding-overlay-hider"},{Y:"div",j:"ytp-ce-expanding-overlay-background"},{Y:"div",j:"ytp-ce-expanding-overlay-content",
C:[{Y:"div",j:"ytp-ce-expanding-overlay-body",C:[{Y:"div",j:"ytp-ce-expanding-overlay-body-padding",C:[{Y:"div",j:"ytp-ce-merchandise-title",L:{dir:g.vj(W.title||"")},NV:W.title},f,{Y:"div",j:"ytp-ce-merchandise-metadata",NV:W.metadata},{Y:"a",d6:["ytp-ce-merchandise-goto","ytp-ce-link"],L:{href:Ge(L,W.targetUrl),target:"_blank",tabindex:"-1"},NV:W.callToAction}]}]}]}]},{Y:"div",j:"ytp-ce-expanding-image",L:Np(W)},{Y:"div",j:"ytp-ce-merchandise-invideo-cta-container",C:[{Y:"div",j:"ytp-ce-merchandise-invideo-cta",
NV:W.callToAction||void 0}]}]},f=new g.G(L)}W.isPlaceholder&&g.$C(f.element,"ytp-ce-placeholder");return f},Np=function(L){if(L.E4)var W=L.E4.thumbnails;
return TPL(W?W[W.length-1].url:null)},TPL=function(L){return L?{style:"background-image: url("+L+")"}:{}},KEO=function(L,W,f){function I(d){d&&(W.listen("blur",function(){d.style.display!="none"&&L.Kl&&d.focus()}),W.D(d,"focus",e),W.D(d,"blur",b))}
function U(d){L.V+=d;L.V>0?(g.$C(W.element,"ytp-ce-force-expand"),cO(L,f.id,!0)):(g.IA(W.element,"ytp-ce-force-expand"),g.IA(W.element,"ytp-ce-element-hover"),cO(L,f.id,!1))}
function e(){U(1)}
function b(){U(-1)}
W.listen("mouseenter",function(){yUv(L,W,f)});
W.listen("mouseleave",function(){gJD(L,W,f)});
L.player.B().K||W.listen("click",function(){g.$C(W.element,"ytp-ce-element-hover")});
W.listen("click",function(d){QEi(L,f,d)});
W.listen("keypress",function(d){QEi(L,f,d)});
W.listen("focus",function(){yUv(L,W,f)});
W.listen("blur",function(){gJD(L,W,f)});
W.listen("touchstart",function(){yUv(L,W,f)});
var E=g.bd("ytp-ce-expanding-overlay-hider",W.element);E&&W.D(E,"touchstart",function(d){d.stopPropagation();g.IA(W.element,"ytp-ce-element-hover");g.IA(W.element,"ytp-ce-force-expand")});
W.listen("keydown",function(d){L.Kl=d.keyCode===9&&!d.shiftKey});
I(g.bd("ytp-sb-subscribe",W.element));I(g.bd("ytp-sb-unsubscribe",W.element));W.listen("focus",e);W.listen("blur",b)},QEi=function(L,W,f){if(W.targetUrl&&(!f||f.type!=="keypress"||f.keyCode===13)){for(var I=f.target;I&&!g.Wj(I,"ytp-ce-element");){g.Wj(I,"subscribe-label")&&jEQ(L,W);
if(g.Wj(I,"ytp-ce-channel-subscribe"))return;I=I.parentElement||null}if(!I||g.Wj(I,"ytp-ce-element-hover")){f.preventDefault();f.stopPropagation();if(I=L.K[W.id])gJD(L,I,W),I.element.blur();if(f.ctrlKey||f.metaKey||W.Wsw==="new")jEQ(L,W),L.player.sendVideoStatsEngageEvent(17,void 0),L.player.pauseVideo(),f=g.ou(Ge(L,W.targetUrl)),f=g.Iu(f),g.R7(f,void 0,W.sessionData);else{var U=g.X8(L.player.B())||L.player.getVideoData().ly,e=function(){var b=Ge(L,W.targetUrl),E=W.sessionData,d=W.watchEndpoint,v=
g.WR(b);U&&v&&(v.v||v.list)?L.player.lK(v.v,E,v.list,!1,void 0,d||void 0):g.pY(b,E)};
jEQ(L,W,function(){L.player.sendVideoStatsEngageEvent(17,e)})}}}},Ge=function(L,W){L=L.player.B();
if(W){if(W.startsWith("//"))return L.protocol+":"+W;if(W.startsWith("/"))return g.QB(L)+W}else return"";return W},yUv=function(L,W,f){g.Wj(W.element,"ytp-ce-element-hover")||(f.type==="VIDEO"||f.type==="PLAYLIST"?g.$C(W.element,"ytp-ce-element-hover"):L.player.B().K?(new g.sn(function(){g.$C(W.element,"ytp-ce-element-hover")},200)).start():g.$C(W.element,"ytp-ce-element-hover"),sU(L,f.LH),cO(L,f.id,!0))},gJD=function(L,W,f){g.IA(W.element,"ytp-ce-element-hover");
g.IA(W.element,"ytp-ce-force-expand");cO(L,f.id,!1)},cO=function(L,W,f){L.N&&(f?L.G.show():L.G.hide());
for(var I=g.n(Object.keys(L.K)),U=I.next();!U.done;U=I.next())U=U.value,U!==W&&g.e2(L.K[U].element,"ytp-ce-element-shadow-show",f)},sU=function(L,W,f){function I(){e||(U++,U===W.length&&(b.stop(),f&&f()))}
if(!W||W.length===0||p6(L))f&&f();else{W=tVC(L,W);var U=0,e=!1,b=new g.sn(function(){e=!0;f&&f()},1E3,L);
b.start();for(L=0;L<W.length;L++)g.Px(W[L],I)}},jEQ=function(L,W,f){sU(L,W.clickUrls,f);
(L=g.z5())&&W.wdU&&g.OO(L,W.visualElement)},tVC=function(L,W){var f=L.player.getVideoData().clientPlaybackNonce;
L=L.player.getCurrentTime().toFixed(2);f={CPN:f,AD_CPN:f,MT:L};L=[];for(var I=0;I<W.length;I++)L.push(PC5(W[I],f));return L},PC5=function(L,W){return L.replace(/%5B[a-zA-Z_:]+%5D|\[[a-zA-Z_:]+\]/g,function(f){var I=unescape(f);
I=I.substring(1,I.length-1);return W[I]?escape(W[I]):f})},JUC=function(L){return typeof L==="string"?L:""},qp=function(L,W,f){for(var I in W)if(W[I]===L)return L;
return f},YRi=function(L,W,f,I){this.value=L;
this.target=W;this.showLinkIcon=f;this.W=I},iX=function(L){return L.value?L.value:null},xL=function(L){if(!L)return null;
var W=g.ou(JUC(L.value));W=g.Iu(W);if(!W)return null;var f=qp(L.target,FEA,"current");if(f==null)L=null;else{var I=L.show_link_icon;L=new YRi(W,f,I==="true"||I==="false"?I==="true":!0,L.pause_on_navigation!=null?L.pause_on_navigation:!0)}return L},aJi=function(L,W,f){this.type=L;
this.trigger=W;this.url=f},R1A=function(L){if(!L)return null;
var W=qp(L.type,CCC),f=qp(L.trigger,p4G);L=L.url;L=Array.isArray(L)&&L.length?L[0]:L;L=xL(L?L:null);return W?new aJi(W,f,L):null},NP5=function(L,W,f,I,U){this.id=L;
this.type=W;this.style=f;this.data=U;this.action=I||[]},GAc=function(L,W){return g.wt(L.action,W)},cUv=function(L,W){this.context=L;
this.W=W},sEA=function(L){return L.customMessage?kL("div","iv-card-message",L.customMessage):""},HO=function(L,W){L="background-image: url("+L+");";
var f=[];W&&f.push(W);return{Y:"div",j:"iv-card-image",L:{style:L},C:f}},qRt=function(L){if(!L.metaInfo||L.metaInfo.length===0)return"";
var W=[];L=g.n(L.metaInfo);for(var f=L.next();!f.done;f=L.next())W.push(kL("li","",f.value));return{Y:"ul",j:"iv-card-meta-info",C:W}},kL=function(L,W,f){W?typeof W==="string"?W={"class":W}:Array.isArray(W)&&(W={"class":W.join(" ")}):W={};
W.dir=g.vj(f);return{Y:L,L:W,NV:f}},irL=function(L){if(!L.customMessage)return"";
var W=["iv-card-action","iv-card-primary-link"],f={};L.Dn&&(W.push("iv-card-action-icon"),f.style="background-image: url("+L.Dn+");");f.dir=g.vj(L.customMessage);var I=[{Y:"span",NV:L.customMessage}];L.showLinkIcon&&(I.push("\u00a0"),I.push({Y:"span",j:"iv-card-link-icon"}));return{Y:"div",d6:W,L:f,C:I}},lX=function(L,W,f,I){if(I){W=g.n(W);
for(var U=W.next();!U.done;U=W.next())L.W(U.value,I,f.id,f.sessionData,f.OS.click,5)}},xIA=function(L,W){this.merchant=L;
this.price=W},kAt=function(L){var W;
(W=L)&&!(W=L.length>1?L.charAt(0)==="/"&&L.charAt(1)!=="/":L==="/")&&(W=L.replace(/^(https?:)?\/\//,"").split("/",1),W=!W||W.length<1||!W[0]?[]:W[0].toLowerCase().split(".").reverse(),W=W[0]==="com"&&W[1]==="youtube"||W[0]==="be"&&W[1]==="youtu");return W?L.indexOf("/redirect?")===-1:!1},HrW=function(L,W){return W?W:kAt(L)?"current":"new"},OU=function(L,W){g.a.call(this);
var f=this;this.element=L;this.context=W;this.m2=!1;this.oh=new Map;this.Cl=new Map;this.context.S.addEventListener(g.iW("annotations_module"),function(I){(I=f.oh.get(I))&&I.apply(f)});
this.context.S.addEventListener(g.xM("annotations_module"),function(I){(I=f.Cl.get(I))&&I.apply(f)})},Lf=function(L,W,f,I,U,e,b){L.context.W.listen(W,"click",function(E){L.CT(f,I,U,e||[],b||0,E)});
L.context.W.listen(W,"touchstart",function(){L.m2=!1});
L.context.W.listen(W,"touchmove",function(){L.m2=!0})},lJ5=function(L){var W;
return((W=g.R(L,g.P2))==null?0:W.url)?g.R(L,g.P2).url:(L=g.R(L,g.VZ))&&L.videoId?(W="/watch?v="+L.videoId,L.playlistId&&(W+="&list="+L.playlistId),L.index&&(W+="&index="+L.index),L.startTimeSeconds&&(W+="&t="+L.startTimeSeconds),W):null},WX=function(L,W,f){return{M9:(L.impressionLoggingUrlsV2s||[]).map(function(I){return I.baseUrl||""}),
click:(f.loggingUrls||[]).map(function(I){return I.baseUrl||""}),
close:(W.dismissLoggingUrlsV2s||[]).map(function(I){return I.baseUrl||""}),
zX:(W.impressionLoggingUrlsV2s||[]).map(function(I){return I.baseUrl||""}),
GT:(W.clickLoggingUrlsV2s||[]).map(function(I){return I.baseUrl||""})}},Orc=function(L,W,f){OU.call(this,W,f);
var I=this;this.S=L;this.eventId=null;this.Tq=this.g6=this.Ow=this.N=this.isInitialized=!1;this.cards=[];this.Nk=this.G=this.FP=this.J=this.Vs=this.W=null;this.Kl=[];this.qV=this.U=this.Uv=this.Yp=null;this.V=0;this.ys=new g.sn(function(){},f.kp.TO?4E3:3E3);
g.C(this,this.ys);this.UH=new g.sn(function(){});
g.C(this,this.UH);this.Rh=new cUv(f,function(U,e,b,E,d,v){Lf(I,U,e,b,E,d,v)});
this.X=new g.G({Y:"div",j:"iv-drawer",L:{id:"iv-drawer"},C:[{Y:"div",j:"iv-drawer-header",L:{"aria-role":"heading"},C:[{Y:"span",j:"iv-drawer-header-text"},{Y:"button",d6:["iv-drawer-close-button","ytp-button"],L:{"aria-label":"\uce74\ub4dc \uc228\uae30\uae30",tabindex:"0"}}]},{Y:"div",j:"iv-drawer-content"}]});g.C(this,this.X);this.T=this.X.element;this.Ll=new g.O5(this.X,330);g.C(this,this.Ll);this.R6=g.bd("iv-drawer-header-text",this.T);this.K=g.bd("iv-drawer-content",this.T);this.addCueRange(0,
f.videoData.lengthSeconds*1E3,"",function(){I.Ow&&$U(I,"YOUTUBE_DRAWER_AUTO_OPEN")},function(){(I.Ow=I.N)&&ff(I)});
this.Hd=new g.XF(this);g.C(this,this.Hd);this.S.addEventListener("videodatachange",this.HC.bind(this))},LeL=function(L,W){W=W.data;
W.autoOpenMs&&L.addCueRange(W.autoOpenMs,0x8000000000000,"",function(){$U(L,"YOUTUBE_DRAWER_AUTO_OPEN")});
W.autoCloseMs&&L.addCueRange(W.autoCloseMs,0x8000000000000,"",function(){ff(L)});
var f=W.headerText;g.My(L.R6,f);L.G&&(L.S.Z("player_tooltip_data_title_killswitch")?L.G.setAttribute("title",f):L.G.setAttribute("data-tooltip-title",f));W.eventId&&(L.eventId=W.eventId);L.Yp=g.Zf(W.trackingParams);L.U=g.Zf(W.closeTrackingParams);L.Uv=g.Zf(W.iconTrackingParams)},WeD=function(L,W){var f=W.cardId?W.cardId:"cr:"+L.V,I=L.S.B().experiments.XP("enable_error_corrections_infocard_web_client");
if(!W.content&&W.teaser.simpleCardTeaserRenderer&&I){var U=W.teaser.simpleCardTeaserRenderer,e=W.icon?W.icon.infoCardIconRenderer:null;if(U.channelAvatar&&U.channelAvatar.thumbnails&&U.channelAvatar.thumbnails.length>0)var b=ID(U.channelAvatar.thumbnails,22,22).url;W={id:f,timestamp:L.V,type:"simple",teaserText:g.d3(U.message),teaserDurationMs:Number(W.cueRanges[0].teaserDurationMs),startMs:Number(W.cueRanges[0].startCardActiveMs),autoOpen:!!W.autoOpen,sessionData:{},sponsored:!1,OS:{},Qh:null,qB:U.trackingParams?
g.Zf(U.trackingParams):null,Uv:e&&e.trackingParams?g.Zf(e.trackingParams):null,imageUrl:"",displayDomain:null,showLinkIcon:!1,Dn:null,title:"",customMessage:"",url:null,onClickCommand:U.onTapCommand||null,eO:b};Uq(L,W)}else{var E;if((E=W.content)==null?0:E.simpleCardContentRenderer){if(!W.cueRanges.length)return;b=(U=W.content)==null?void 0:U.simpleCardContentRenderer;U=W.teaser.simpleCardTeaserRenderer;e=W.icon?W.icon.infoCardIconRenderer:null;W={id:f,timestamp:L.V,type:"simple",teaserText:g.d3(U.message),
teaserDurationMs:Number(W.cueRanges[0].teaserDurationMs),startMs:Number(W.cueRanges[0].startCardActiveMs),autoOpen:!!W.autoOpen,sessionData:ew(L,f,W,b),sponsored:!1,OS:WX(b,U,b.command),Qh:b.trackingParams?g.Zf(b.trackingParams):null,qB:U.trackingParams?g.Zf(U.trackingParams):null,Uv:e&&e.trackingParams?g.Zf(e.trackingParams):null,imageUrl:ID(b.image.thumbnails,290,290).url,displayDomain:b.displayDomain?g.d3(b.displayDomain):null,showLinkIcon:!!b.showLinkIcon,Dn:null,title:b.title?g.d3(b.title):"",
customMessage:b.callToAction?g.d3(b.callToAction):"",url:g.R(b.command,g.P2).url?xL({pause_on_navigation:!L.context.videoData.isLivePlayback,target:"new",value:g.R(b.command,g.P2).url}):null,onClickCommand:null};Uq(L,W)}else{var d;if((d=W.content)==null?0:d.collaboratorInfoCardContentRenderer){if(!W.cueRanges.length)return;b=(e=W.content)==null?void 0:e.collaboratorInfoCardContentRenderer;U=W.teaser.simpleCardTeaserRenderer;e=W.icon?W.icon.infoCardIconRenderer:null;W={id:f,timestamp:L.V,type:"collaborator",
teaserText:g.d3(U.message),teaserDurationMs:Number(W.cueRanges[0].teaserDurationMs),startMs:Number(W.cueRanges[0].startCardActiveMs),autoOpen:!!W.autoOpen,sessionData:ew(L,f,W,b),sponsored:!1,OS:WX(b,U,b.endpoint),Qh:b.trackingParams?g.Zf(b.trackingParams):null,qB:U.trackingParams?g.Zf(U.trackingParams):null,Uv:e&&e.trackingParams?g.Zf(e.trackingParams):null,channelId:g.R(b.endpoint,g.l5).browseId,customMessage:b.customText?g.d3(b.customText):null,profileImageUrl:ID(b.channelAvatar.thumbnails,290,
290).url,title:b.channelName?g.d3(b.channelName):"",metaInfo:[b.subscriberCountText?g.d3(b.subscriberCountText):""],url:xL({pause_on_navigation:!L.context.videoData.isLivePlayback,target:"new",value:g.R(b.endpoint,g.l5).canonicalBaseUrl?g.R(b.endpoint,g.l5).canonicalBaseUrl:"/channel/"+g.R(b.endpoint,g.l5).browseId}),onClickCommand:null};Uq(L,W)}else{var v;if((v=W.content)==null?0:v.playlistInfoCardContentRenderer){if(!W.cueRanges.length)return;var r;b=(r=W.content)==null?void 0:r.playlistInfoCardContentRenderer;
U=W.teaser.simpleCardTeaserRenderer;e=W.icon?W.icon.infoCardIconRenderer:null;W={id:f,timestamp:L.V,type:"playlist",teaserText:g.d3(U.message),teaserDurationMs:Number(W.cueRanges[0].teaserDurationMs),startMs:Number(W.cueRanges[0].startCardActiveMs),autoOpen:!!W.autoOpen,sessionData:ew(L,f,W,b),sponsored:!1,OS:WX(b,U,b.action),Qh:b.trackingParams?g.Zf(b.trackingParams):null,qB:U.trackingParams?g.Zf(U.trackingParams):null,Uv:e&&e.trackingParams?g.Zf(e.trackingParams):null,XN:ID(b.playlistThumbnail.thumbnails,
258,290).url,customMessage:b.customMessage?g.d3(b.customMessage):null,playlistVideoCount:g.d3(b.playlistVideoCount),title:b.playlistTitle?g.d3(b.playlistTitle):"",metaInfo:[b.channelName?g.d3(b.channelName):"",b.videoCountText?g.d3(b.videoCountText):""],url:xL({pause_on_navigation:!L.context.videoData.isLivePlayback,target:"new",value:lJ5(b.action)}),onClickCommand:null};Uq(L,W)}else{var B;if((B=W.content)==null?0:B.videoInfoCardContentRenderer){if(!W.cueRanges.length)return;var A;b=(A=W.content)==
null?void 0:A.videoInfoCardContentRenderer;U=W.teaser.simpleCardTeaserRenderer;e=W.icon?W.icon.infoCardIconRenderer:null;W={id:f,timestamp:L.V,type:"video",teaserText:g.d3(U.message),teaserDurationMs:Number(W.cueRanges[0].teaserDurationMs),startMs:Number(W.cueRanges[0].startCardActiveMs),autoOpen:!!W.autoOpen,sessionData:ew(L,f,W,b),sponsored:!1,OS:WX(b,U,b.action),Qh:b.trackingParams?g.Zf(b.trackingParams):null,qB:U.trackingParams?g.Zf(U.trackingParams):null,Uv:e&&e.trackingParams?g.Zf(e.trackingParams):
null,XN:ID(b.videoThumbnail.thumbnails,258,290).url,videoDuration:b.lengthString?g.d3(b.lengthString):null,customMessage:b.customMessage?g.d3(b.customMessage):null,title:b.videoTitle?g.d3(b.videoTitle):"",metaInfo:[b.channelName?g.d3(b.channelName):"",b.viewCountText?g.d3(b.viewCountText):""],isLiveNow:!!b.badge,url:xL({pause_on_navigation:!L.context.videoData.isLivePlayback,target:"new",value:lJ5(b.action)}),onClickCommand:null};Uq(L,W)}}}}}L.V++},ID=function(L,W,f){for(var I=-1,U=-1,e=0;e<L.length;e++){if(L[e].height===
W||L[e].width===f)return L[e];
((L[e].height||0)<W||(L[e].width||0)<f)&&(I<0||(L[I].height||0)<(L[e].height||0)||(L[I].width||0)<(L[e].width||0))?I=e:((L[e].height||0)>=W||(L[e].width||0)>=f)&&(U<0||(L[U].height||0)>(L[e].height||0)||(L[U].width||0)>(L[e].width||0))&&(U=e)}return L[U>=0?U:I]},ew=function(L,W,f,I){return{feature:f.feature?f.feature:"cards",
src_vid:L.context.videoData.videoId,annotation_id:W,ei:L.context.videoData.eventId||"",itct:I.trackingParams||""}},fyL=function(L,W){if(W=$NW(L,W))W===L.W&&(L.W=null),L.S.removeCueRange(W.bX.id),g.wy(W.PA),g.XO(L.cards,W),L.FT(),oD(L)},$U=function(L,W,f){if(!L.N){L.Ll.show();
L.Vs=new g.sn(function(){g.$C(L.context.S.getRootNode(),g.nH.IV_DRAWER_OPEN)},0);
L.Vs.start();L.Hd.D(L.K,"mousewheel",function(b){L.ys.start();b.preventDefault();b=b||window.event;var E=0;b.type=="MozMousePixelScroll"?E=0==(b.axis==b.HORIZONTAL_AXIS)?b.detail:0:window.opera?E=b.detail:E=b.wheelDelta%120==0?"WebkitTransform"in document.documentElement.style?window.chrome&&navigator.platform.indexOf("Mac")==0?b.wheelDeltaY/-30:b.wheelDeltaY/-1.2:b.wheelDelta/-1.6:b.wheelDeltaY/-3;if(b=E)L.K.scrollTop+=b});
L.N=!0;var I=g.z5();I&&L.Yp&&L.U&&g.Hd(I,[L.Yp,L.U]);W={TRIGGER_TYPE:W};for(var U=g.n(L.cards),e=U.next();!e.done;e=U.next())e=e.value,e.Yj||(e.Yj=!0,Iyi(L.context.logger,e.bX.OS.M9,W)),I&&g.Hd(I,[e.bX.Qh]);QY(L.S);f&&(L.J=new g.sn(function(){L.FP=L.G;L.Nk.focus()},330),L.J.start())}},ff=function(L){L.N&&(L.Ll.hide(),g.T4(L.Hd),g.IA(L.context.S.getRootNode(),g.nH.IV_DRAWER_OPEN),L.N=!1,QY(L.S),L.J&&L.J.stop(),L.J=new g.sn(function(){L.FP&&(L.FP.focus(),L.FP=null)},330),L.J.start())},UNO=function(L){g.fZ(L.Mk(),
[g.nH.STOP_EVENT_PROPAGATION,
"iv-drawer-manager"]);g.Ln(L.S,L.T,5);L.zj();L.G=g.bd("ytp-cards-button",L.S.getRootNode());L.Nk=g.bd("iv-drawer-close-button",L.T);L.isInitialized=!0},eoD=function(L){L.Kl.push(g.OE("iv-teaser-shown",L.lY,L));
L.Kl.push(g.OE("iv-teaser-hidden",L.Hlh,L));L.Kl.push(g.OE("iv-teaser-clicked",L.wq,L));L.Tq=!0},o6i=function(L,W){var f;
return W.onClickCommand&&((f=g.R(W.onClickCommand,g.t9O))==null?void 0:f.targetId)==="engagement-panel-error-corrections"?(L.qV=W,!0):!1},bwn=function(L,W){L.qV=W;
var f=L.S.getVideoData();if(!f)return!1;f=g.WD(f);if(f==null?0:f.markersMap)for(var I,U=0;((I=f)==null?void 0:I.markersMap.length)>U;U++){var e=void 0,b=(e=f)==null?void 0:e.markersMap[U];if(b.key==="ERROR_CORRECTION_MARKERS"&&(e=void 0,(b=(e=b.value)==null?void 0:e.markers)&&b.length>0))return I=void 0,W.startMs=((I=g.R(b[0],g.kCp))==null?void 0:I.timeRangeStartMillis)||0,L.qV=null,!0}return!1},Uq=function(L,W){if(!o6i(L,W)||bwn(L,W)){var f=hov(L,W);
if(f){var I={bX:W,PA:f.element,Yj:!1};if(W.onClickCommand)L.S.Z("web_infocards_teaser_show_logging_fix")&&(L.Tq||eoD(L),fyL(L,W.id),f=L.findLastIndex(I),g.an(L.cards,f,0,I));else{L.isInitialized||UNO(L);fyL(L,W.id);var U=L.findLastIndex(I);g.an(L.cards,U,0,I);f.OH(L.K,U);L.FT()}W.autoOpen?L.addCueRange(W.startMs,0x8000000000000,W.id,function(){L.N||(L.W=I,oD(L),E6G(L,I),$U(L,"YOUTUBE_DRAWER_AUTO_OPEN",!1))}):(f=L.context.S.getCurrentTime()*1E3,f<5E3&&f>W.startMs&&dNO(L,I),L.addCueRange(W.startMs,
W.startMs+1,W.id,function(){dNO(L,I)}),oD(L))}}},hov=function(L,W){switch(W.type){case "simple":L=L.Rh;
var f=W.displayDomain?{Y:"div",j:"iv-card-image-text",NV:W.displayDomain}:void 0;var I=irL(W);f={Y:"div",d6:["iv-card"],C:[{Y:"a",j:"iv-click-target",L:{href:W.url?iX(W.url)||"":""},C:[HO(W.imageUrl,f),{Y:"div",j:"iv-card-content",C:[kL("h2",void 0,W.title),I]}]}]};f=new g.G(f);lX(L,g.e9("iv-click-target",f.element),W,W.url);W=f;break;case "collaborator":L=L.Rh;f={Y:"div",d6:["iv-card","iv-card-channel"],C:[{Y:"a",d6:["iv-click-target"],L:{href:iX(W.url)||"","data-ytid":W.channelId},C:[HO(W.profileImageUrl),
{Y:"div",j:"iv-card-content",C:[sEA(W),{Y:"h2",j:"iv-card-primary-link",NV:W.title},qRt(W)]}]}]};f=new g.G(f);lX(L,g.e9("iv-click-target",f.element),W,W.url);W=f;break;case "playlist":L=L.Rh;f={Y:"div",d6:["iv-card","iv-card-playlist"],C:[{Y:"a",j:"iv-click-target",L:{href:iX(W.url)||""},C:[HO(W.XN,{Y:"div",j:"iv-card-image-overlay",C:[{Y:"span",j:"iv-card-playlist-video-count",NV:W.playlistVideoCount}]}),{Y:"div",j:"iv-card-content",C:[sEA(W),kL("h2","iv-card-primary-link",W.title),qRt(W)]}]}]};
f=new g.G(f);lX(L,g.e9("iv-click-target",f.element),W,W.url);W=f;break;case "productListing":L=L.Rh;var U=W.offers.length!=0;f=["iv-card"];I="";var e=irL(W);U&&(f.push("iv-card-product-listing"),I="iv-card-primary-link",e=W.offers[0],U=[],e.price&&U.push({Y:"div",j:"iv-card-offer-price",NV:e.price}),e.merchant&&U.push({Y:"div",j:"iv-card-offer-merchant",NV:e.merchant}),e={Y:"div",C:U});U=W.url?iX(W.url)||"":"";f={Y:"div",d6:f,L:{tabindex:"0"},C:[{Y:"a",d6:["iv-card-image","iv-click-target"],L:{style:"background-image: url("+
W.imageUrl+");",href:U,"aria-hidden":"true",tabindex:"-1"}},{Y:"div",j:"iv-card-content",C:[W.sponsored?{Y:"div",j:"iv-card-sponsored",C:["\uc2a4\ud3f0\uc11c",{Y:"div",j:"iv-ad-info-container",C:[{Y:"div",j:"iv-ad-info",NV:"{{adInfo}}"},{Y:"div",j:"iv-ad-info-icon-container",C:[{Y:"div",j:"iv-ad-info-icon"},{Y:"div",j:"iv-ad-info-callout"}]}]}]}:"",{Y:"a",j:"iv-click-target",L:{href:U},C:[kL("h2",I,W.title),e]}]}]};f=new g.G(f);I=g.Bq("span");g.My(I,"\ub3d9\uc601\uc0c1\uacfc \uad00\ub828\uc774 \uc788\ub294 \uac83\uc73c\ub85c \ubcf4\uc5ec \uc81c\ud488\uc774 \ud45c\uc2dc\ub418\uc5c8\uc2b5\ub2c8\ub2e4. Google\uc5d0\uc11c \ud310\ub9e4\uc790\ub85c\ubd80\ud130 \ubcf4\uc0c1\uc744 \ubc1b\uc744 \uc218\ub3c4 \uc788\uc2b5\ub2c8\ub2e4.");
f.eS(I,"adInfo");lX(L,g.e9("iv-click-target",f.element),W,W.url);W=f;break;case "video":L=L.Rh;I=W.videoDuration?{Y:"span",j:"iv-card-video-duration",NV:W.videoDuration}:void 0;e=W.isLiveNow?{Y:"span",d6:["yt-badge","yt-badge-live"],NV:"\uc2e4\uc2dc\uac04"}:null;U={Y:"div",d6:["iv-card","iv-card-video"],C:[{Y:"a",j:"iv-click-target",L:{href:((f=W.url)==null?void 0:iX(f))||""},C:[HO(W.XN,I),{Y:"div",j:"iv-card-content",C:[sEA(W),kL("h2","iv-card-primary-link",W.title),qRt(W),e]}]}]};f=new g.G(U);lX(L,
g.e9("iv-click-target",f.element),W,W.url);W=f;break;default:return null}return W},v6c=function(L){if(L.W)return L.W.bX.type==="productListing";
if(L.S.Z("enable_wn_infocards")){var W;return!((W=L.cards)==null||!W.length)&&g.wo(L.cards,function(f){return f.bX.type==="productListing"})}return g.wo(L.cards,function(f){return f.bX.type==="productListing"})},oD=function(L){g.e2(L.S.getRootNode(),"ytp-cards-shopping-active",v6c(L))},dNO=function(L,W){if(!g.Wj(L.S.getRootNode(),"ytp-cards-teaser-shown")){if(L.W!==W){var f=g.z5(),I=L.W?L.W.bX.Uv:L.Uv;
f&&I&&g.lA(f,[I]);L.W=W;oD(L)}(f=L.isInitialized&&L.Mk().style.display=="none")||(f=L.context.S.getPlayerState(),I=f===0&&L.context.S.getCurrentTime()===0,f=!(f===1||f===3||I));if(!f&&W.bX.teaserDurationMs){var U;f={teaserText:W.bX.teaserText,durationMs:W.bX.teaserDurationMs,onClickCommand:W.bX.onClickCommand,eO:(U=W.bX.eO)!=null?U:null};L.S.j9(!0,f)}L.UH.isActive()||((!L.N||!L.ys.isActive()&&L.g6)&&E6G(L,W),L.UH.start(910+W.bX.teaserDurationMs))}},E6G=function(L,W){L.X.Pn?(W=new YL([0,
L.K.scrollTop],[0,W.PA.offsetTop],600,DID),L.context.N.listen(W,"animate",function(f){L.K.scrollTop=f.y}),L.context.N.listen(W,"finish",function(f){L.K.scrollTop=f.y}),W.play()):(L.X.DE(!0),L.K.scrollTop=W.PA.offsetTop,L.X.DE(!1))},bg=function(L){return L.W&&L.W.bX?L.W.bX:L.cards[0]&&L.cards[0].bX?L.cards[0].bX:null},$NW=function(L,W){return g.wt(L.cards,function(f){return f.bX.id===W})},hQ=function(L,W,f){OU.call(this,L,W);
this.annotation=f;this.isActive=!1},r45=function(L){var W=L.annotation.data;
"start_ms"in W&&"end_ms"in W&&L.addCueRange(Number(W.start_ms),Number(W.end_ms),L.annotation.id,function(){L.show()},function(){L.hide()})},Eq=function(L,W,f){hQ.call(this,L,W,f);
this.K=null;this.V=!1;this.N=null;this.T=!1;this.W=this.J=this.G=null},BHO=function(L,W){var f=f===void 0?0:f;
var I=h1c(W).width;g.kk(W,I);f=new SRQ(W,[I,W.offsetTop],[I-I-f,W.offsetTop],200,Zrc);g.C(L,f);L.context.N.listen(f,"begin",function(){g.$V(W,!0)});
f.play()},Zwv=function(L,W){if(W.channel_name){var f=L.createElement({Y:"div",
d6:["iv-branding-context-name"],NV:W.channel_name}),I=L.createElement({Y:"div",d6:["iv-branding-context-subscribe"]}),U=W.standalone_subscribe_button_data;U&&(L.W=new g.eI(U.subscribeText,U.subscribeCount,U.unsubscribeText,U.unsubscribeCount,!!U.enabled,!!U.classic,W.channel_id,!!U.subscribed,U.feature,W.session_data.itct,L.context.S,!1),L.W.OH(I));var e=L.createElement({Y:"div",d6:["iv-branding-context-subscribe-caret"]}),b=L.createElement({Y:"div",d6:["branding-context-container-inner"]});b.appendChild(e);
b.appendChild(f);b.appendChild(I);g.$V(b,!1);var E=L.createElement({Y:"div",d6:["branding-context-container-outer"]});E.appendChild(b);g.Ga(E,"right",W.image_width+"px");g.S9(L.Mk(),E);L.N=new g.sn(function(){A4c(L,b,E)},500);
g.C(L,L.N);L.context.W.listen(L.Mk(),"mouseover",function(){Suc(L,b,E,e,W.image_height)});
L.context.W.listen(L.Mk(),"mouseout",function(){L.N.start()})}},Suc=function(L,W,f,I,U){L.N.stop();
if(!L.T){var e=g.Wb(W);L.W||(W.style.width=g.xk(e.width,!0),f.style.width=g.xk(e.width,!0));g.Ga(I,"top",e.height-Math.max(Math.min(e.height,U)/2+10,20)+"px");g.Ga(I,"right","1px");L.T=!0;g.$V(W,!0);L.G=new g.sn(function(){g.$C(this.Mk(),"iv-branding-active")},0,L);
L.G.start()}},A4c=function(L,W,f){g.IA(L.Mk(),"iv-branding-active");
L.J=new g.sn(function(){g.$V(W,!1);L.W||(f.style.width=g.xk(0,!0))},250);
L.J.start();L.T=!1},DND=function(L,W,f,I,U,e,b){this.W=L;
this.N=W;this.kp=f;this.videoData=I;this.logger=U;this.S=e;this.K=b},w8n=function(L,W,f){hQ.call(this,L,W,f);
var I=this;this.U=this.isCollapsed=this.X=!1;this.J=5E3;this.K=this.N=this.W=this.T=null;this.V=this.createElement({Y:"div",d6:["iv-promo-contents"]});this.G=new g.sn(function(){I.W.setAttribute("aria-hidden","true");g.$V(I.N,!1);g.$V(I.K,!0)},700,this);
g.C(this,this.G)},MoC=function(L){var W=L.annotation.data;
if(L.annotation.style==="cta")var f=6;else if(L.annotation.style==="video"||L.annotation.style==="playlist")f=7;L.J=W.collapsedelay_ms||L.J;var I=["iv-promo","iv-promo-inactive"];L.Mk().setAttribute("aria-hidden","true");L.Mk().setAttribute("aria-label","\ud504\ub85c\ubaa8\uc158");L.Mk().tabIndex=0;var U=L.annotation.vF(),e=W.image_url;if(e){var b=L.createElement({Y:"div",d6:["iv-promo-img","iv-click-target"]});e=L.createElement({Y:"img",L:{src:e,"aria-hidden":"true"}});b.appendChild(e);W.video_duration&&
!W.is_live?(e=L.createElement({Y:"span",j:"iv-promo-video-duration",NV:W.video_duration}),b.appendChild(e)):W.playlist_length&&(e=L.createElement({Y:"span",j:"iv-promo-playlist-length",NV:W.playlist_length.toString()}),b.appendChild(e));U&&Lf(L,b,U,L.annotation.id,W.session_data,void 0,f)}U?(e=L.createElement({Y:"a",j:"iv-promo-txt"}),g.h9(e,iX(U)),L.W=e):L.W=L.createElement({Y:"div",j:"iv-promo-txt"});switch(L.annotation.style){case "cta":case "website":var E=L.createElement({Y:"p",C:[{Y:"strong",
NV:W.text_line_1}]});var d=L.createElement({Y:"p",C:[{Y:"span",j:"iv-promo-link",NV:W.text_line_2}]});if(e=W.text_line_3){I.push("iv-promo-website-card-cta-redesign");var v=L.createElement({Y:"button",d6:["iv-promo-round-expand-icon","ytp-button"]});e=L.createElement({Y:"button",d6:["iv-button","iv-promo-button"],C:[{Y:"span",j:"iv-button-content",NV:e}]});var r=L.createElement({Y:"div",j:"iv-promo-button-container"});r.appendChild(e);U&&Lf(L,L.Mk(),U,L.annotation.id,W.session_data,void 0,f)}g.$C(L.W,
"iv-click-target");U&&Lf(L,L.W,U,L.annotation.id,W.session_data,void 0,f);break;case "playlist":case "video":E=L.createElement({Y:"p",C:[{Y:"span",NV:W.text_line_1}]}),d=L.createElement({Y:"p",C:[{Y:"strong",NV:W.text_line_2}]}),W.is_live&&(E=d,d=L.createElement({Y:"span",d6:["yt-badge","iv-promo-badge-live"],NV:"\uc2e4\uc2dc\uac04"})),g.$C(L.W,"iv-click-target"),U&&Lf(L,L.W,U,L.annotation.id,W.session_data,void 0,f),I.push("iv-promo-video")}E&&L.W.appendChild(E);d&&L.W.appendChild(d);L.V.appendChild(L.W);
r&&L.V.appendChild(r);f=L.createElement({Y:"div",j:"iv-promo-actions"});L.K=L.createElement({Y:"button",d6:["iv-promo-expand","ytp-button"]});L.K.title="\ud655\uc7a5";L.context.W.listen(L.K,"click",function(B){zoL(L,5E3,B)});
f.appendChild(L.K);g.$V(L.K,!1);L.context.W.listen(L.Mk(),"mouseover",L.dI,L);L.context.W.listen(L.Mk(),"mouseout",L.Mh,L);L.context.W.listen(L.Mk(),"touchend",function(B){zoL(L,5E3,B)});
L.N=L.createElement({Y:"button",d6:["iv-promo-close","ytp-button"]});L.N.title="\ub2eb\uae30";L.context.W.listen(L.N,"click",L.annotation.style==="cta"&&W.text_line_3?L.YW:L.PG,L);f.appendChild(L.N);g.fZ(L.Mk(),I);b&&(g.S9(L.Mk(),b),v&&b.appendChild(v));g.S9(L.Mk(),L.V);g.S9(L.Mk(),f)},zoL=function(L,W,f){f.stopPropagation();
n6O(L);X85(L,W);L.W.focus()},Voc=function(L){L.isCollapsed||L.U||L.T||(g.$C(L.Mk(),"iv-promo-collapsed"),L.isCollapsed=!0,L.G.start())},n6O=function(L){L.G.stop();
L.isCollapsed&&(g.UF(L.Mk(),["iv-promo-collapsed","iv-promo-collapsed-no-delay"]),L.isCollapsed=!1,L.W&&L.W.removeAttribute("aria-hidden"),g.$V(L.K,!1),g.$V(L.N,!0))},X85=function(L,W){L.T||(L.T=g.Fm(function(){mNt(this);
Voc(this)},W,L))},mNt=function(L){L.T&&(g.lp.clearTimeout(L.T),L.T=null)},uWt=function(L){this.S=L},Iyi=function(L,W,f){W&&(f?d9(L,W.map(function(I){return g.KN(I,f)})):d9(L,W))},d9=function(L,W,f,I){var U=1,e=void 0,b=-1;
if(f){var E=!1;e=function(){U--;U||E||(clearTimeout(b),E=!0,f())};
b=setTimeout(function(){E=!0;f()},1E3)}W=g.n(W||[]);
for(var d=W.next();!d.done;d=W.next())d=d.value,U++,g.Px(d,e);I&&(U++,I!==0&&L.S.sendVideoStatsEngageEvent(I,e))},y45=function(L){g.ux.call(this,L);
var W=this;this.Kl=this.U=!1;this.loadNumber=0;this.J={};this.logger=new uWt(this.player);this.T=new g.XF(this);this.G=this.V=null;this.events=new g.XF(this);this.rW=this.X=this.W=null;this.qV=[];g.C(this,this.T);this.T.D(this.player,"onVideoAreaChange",function(){W.publish("onVideoAreaChange")});
this.T.D(this.player,"onHideControls",function(){W.publish("onHideControls")});
this.T.D(this.player,"onShowControls",function(){W.publish("onShowControls")});
this.T.D(this.player,"resize",function(e){W.publish("resize",e)});
this.T.D(this.player,"presentingplayerstatechange",function(e){W.publish("presentingplayerstatechange",e)});
this.subscribe("presentingplayerstatechange",this.uY,this);this.subscribe("resize",this.HY,this);this.player.B().g6.subscribe("vast_info_card_add",this.FD,this);g.C(this,this.events);this.Rh=this.createElement({Y:"div",j:"video-custom-annotations"});this.K=new g.G({Y:"div",d6:["ytp-player-content","ytp-iv-player-content"]});g.C(this,this.K);g.Ln(this.player,this.K.element,4);this.K.hide();this.N=new g.G({Y:"div",d6:["ytp-iv-video-content"]});g.C(this,this.N);L=this.createElement({Y:"div",j:"video-annotations"});
L.appendChild(this.Rh);this.N.element.appendChild(L);this.UN()&&this.load();var f=this.createElement({Y:"style"});(g.Ur("HEAD")[0]||document.body).appendChild(f);this.addOnDisposeCallback(function(){g.wy(f)});
if(L=f.sheet){for(var I=g.n(Ken),U=I.next();!U.done;U=I.next())L.insertRule(U.value,0);I=g.n(THD);for(U=I.next();!U.done;U=I.next())L.insertRule(U.value,0)}},g6L=function(L){L=L.createElement({Y:"div",
d6:["annotation","annotation-type-custom"]});g.$V(L,!1);return L},QrO=function(L,W){W=!W.isCued()&&!g.x(W,1024);
L.K.DE(W);L.N.DE(W)},jr5=function(L,W,f){L.U=!0;
L.G=g.V$(W,f)},toA=function(L,W){for(var f={},I=g.n(W.attributes),U=I.next();!U.done;U=I.next())U=U.value,f[U.name]=U.nodeValue;
for(I=0;I<W.childNodes.length;I++)if(U=W.childNodes[I],g.In(U)&&U.nodeType==1){if(f[U.tagName])var e=f[U.tagName];else if(U.tagName==="data"){U.childNodes.length>0&&(e=U.childNodes[0].nodeValue,f[U.tagName]=typeof e==="string"?e.trim():e);continue}else e=[],f[U.tagName]=e;U&&U.tagName==="TEXT"?U.childNodes.length===1&&U.childNodes[0].nodeType===3?e.push(U.childNodes[0].nodeValue):e.push(""):U&&e.push(toA(L,U))}return f},Fec=function(L){var W=L.player.getVideoData();
if(W.Hd){var f=L.player.B().g6.get(W.videoId);if(f){var I={format:"XML",urlParams:{},method:"POST",withCredentials:!0,onFinish:function(U,e,b){U=L.loadNumber;e=W.videoId;L.loaded&&L.loadNumber===U&&L.player.getVideoData().videoId===e&&(b=g.vR(b)&&b.responseXML?b.responseXML:null)&&PNL(L,b)}};
g.H3()&&(I.onFinish=J4t(L,I.onFinish));I.postParams={ic_only:"1"};YuO(I,f);L.U=!0;g.V$(W.Hd,I)}}},YuO=function(L,W){L.method="POST";
L.postParams=L.postParams||{};W.ao&&(L.postParams.ic_coll=W.ao);W.Yg&&(L.postParams.ic_xml=W.Yg);W.pk&&(L.postParams.ic_track=W.pk)},ayA=function(L){var W=new g.G({Y:"div"});
g.$V(W.element,!1);var f=new Orc(L.player,W.element,vX(L));g.C(f,W);W.OH(L.K.element);f.QZ();return f},p8i=function(L,W){var f,I;
if(W=(f=W.getWatchNextResponse())==null?void 0:(I=f.cards)==null?void 0:I.cardCollectionRenderer)L.Kl=!0,CNc(L,W),W.headerText&&L.rW&&(f=g.d3(W.headerText),L.player.Z("player_tooltip_data_title_killswitch")?L.rW.setAttribute("title",f):L.rW.setAttribute("data-tooltip-title",f))},vX=function(L){if(!L.X){var W=new w4t(L);
g.C(L,W);var f=new g.A0(L);g.C(L,f);L.X=new DND(W,f,L.player.B(),L.player.getVideoData(),L.logger,L.player,L.Su)}return L.X},PNL=function(L,W){var f=!1,I=W.getElementsByTagName("annotations");
if(I&&!(I.length<1)&&(I=I[0].getAttribute("itct"))){var U=g.z5();if(U){var e=g.wE();e&&g.xI(g.pm)(void 0,U,e,[g.Zf(I)])}}W=W.getElementsByTagName("annotation");for(I=0;I<W.length;I++){e=toA(L,W[I]);U=null;try{if(e){var b=e.id,E=/.+/;var d=typeof b==="string"&&E!=null&&b!=null&&b.match(E)?b:"";var v=qp(e.type,Roc),r=qp(e.style,NHn),B=JUC(e.data),A=B.length!==0?JSON.parse(B):{};var S=e.action;e=R1A;if(S==null)var Z=null;else if(g.fQ(S)){E=[];for(var M=g.n(S),m=M.next();!m.done;m=M.next()){var T=e(m.value);
T&&E.push(T)}Z=E}else{var K=e(S);Z=K?[K]:[]}U=d&&v?new NP5(d,v,r,Z,A):null}else U=null}catch(hj){}if(U)if(U.type==="branding"||U.type==="promotion"){e=L;E=U;var P=g6L(e),F=null;switch(E.type){case "branding":if(e.player.B().Ej)break;e.player.Z("web_player_overlay_positioned_layout")?(P.setAttribute("data-overlay-order","11"),e.player.tX(P,4,!0)):e.K.element.appendChild(P);F=new Eq(P,vX(e),E);break;case "promotion":g.Ln(e.player,P,4),F=new w8n(P,vX(e),E)}F&&F.QZ();if(e=F)g.C(L,e),L.J[U.id]=e}else if(U.type===
"card"||U.type==="drawer"){L.W||(L.W=ayA(L),g.C(L,L.W));if(U.type==="card"){P=L.W;var p=(f=U)&&f.data&&f.data.card_type;U=f.data;if(p)switch(e=U.tracking||{},e={M9:e.impression,click:e.click,close:e.close,zX:e.teaser_impression,GT:e.teaser_click},E=U.tracking_params||{},F=null,p){case "collaborator":f={id:f.id,timestamp:U.timestamp||0,type:U.card_type,teaserText:U.teaser_text,teaserDurationMs:U.teaser_duration_ms,startMs:U.start_ms,autoOpen:U.auto_open||!1,sessionData:U.session_data||{},sponsored:U.sponsored||
!1,OS:e,Qh:E.card?g.Zf(E.card):null,qB:E.teaser?g.Zf(E.teaser):null,Uv:E.icon?g.Zf(E.icon):null,channelId:U.channel_id,customMessage:U.custom_message?U.custom_message:null,profileImageUrl:U.image_url,title:U.title,metaInfo:U.meta_info,url:xL({pause_on_navigation:U.pause_on_navigation,target:U.target||"new",value:U.url}),onClickCommand:null};Uq(P,f);break;case "playlist":f={id:f.id,timestamp:U.timestamp||0,type:U.card_type,teaserText:U.teaser_text,teaserDurationMs:U.teaser_duration_ms,startMs:U.start_ms,
autoOpen:U.auto_open||!1,sessionData:U.session_data||{},sponsored:U.sponsored||!1,OS:e,Qh:E.card?g.Zf(E.card):null,qB:E.teaser?g.Zf(E.teaser):null,Uv:E.icon?g.Zf(E.icon):null,XN:U.image_url,playlistVideoCount:U.playlist_video_count,customMessage:U.custom_message?U.custom_message:null,title:U.title,metaInfo:U.meta_info,url:xL({pause_on_navigation:U.pause_on_navigation,target:U.target||"new",value:U.url}),onClickCommand:null};Uq(P,f);break;case "productListing":U.signin_url&&(F=xL({target:"current",
value:U.signin_url}));p=[];for(var H=U.offers||[],q=0;q<H.length;q++)p.push(new xIA(g.g0(H[q].merchant),g.g0(H[q].price)));f={id:f.id,timestamp:U.timestamp||0,type:U.card_type,teaserText:U.teaser_text,teaserDurationMs:U.teaser_duration_ms,startMs:U.start_ms,autoOpen:U.auto_open||!1,sessionData:U.session_data||{},sponsored:U.sponsored||!1,OS:e,Qh:E.card?g.Zf(E.card):null,qB:E.teaser?g.Zf(E.teaser):null,Uv:E.icon?g.Zf(E.icon):null,imageUrl:U.image_url,displayDomain:U.display_domain?U.display_domain:
null,showLinkIcon:!!U.show_link_icon,Dn:U.button_icon_url?U.button_icon_url:null,title:U.title,customMessage:U.custom_message?U.custom_message:null,url:xL({pause_on_navigation:U.pause_on_navigation,target:U.target||"new",value:U.url}),zkp:F,u6w:U.signin_title?U.signin_title:void 0,lSe:U.signin_message?U.signin_message:void 0,offers:p,onClickCommand:null};Uq(P,f);break;case "simple":f={id:f.id,timestamp:U.timestamp||0,type:U.card_type,teaserText:U.teaser_text,teaserDurationMs:U.teaser_duration_ms,
startMs:U.start_ms,autoOpen:U.auto_open||!1,sessionData:U.session_data||{},sponsored:U.sponsored||!1,OS:e,Qh:E.card?g.Zf(E.card):null,qB:E.teaser?g.Zf(E.teaser):null,Uv:E.icon?g.Zf(E.icon):null,imageUrl:U.image_url,displayDomain:U.display_domain?U.display_domain:null,showLinkIcon:!!U.show_link_icon,Dn:U.button_icon_url?U.button_icon_url:null,title:U.title,customMessage:U.custom_message?U.custom_message:null,url:xL({pause_on_navigation:U.pause_on_navigation,target:U.target||"new",value:U.url}),onClickCommand:null};
Uq(P,f);break;case "video":f={id:f.id,timestamp:U.timestamp||0,type:U.card_type,teaserText:U.teaser_text,teaserDurationMs:U.teaser_duration_ms,startMs:U.start_ms,autoOpen:U.auto_open||!1,sessionData:U.session_data||{},sponsored:U.sponsored||!1,OS:e,Qh:E.card?g.Zf(E.card):null,qB:E.teaser?g.Zf(E.teaser):null,Uv:E.icon?g.Zf(E.icon):null,XN:U.image_url,videoDuration:U.video_duration||null,customMessage:U.custom_message?U.custom_message:null,title:U.title,metaInfo:U.meta_info,isLiveNow:!!U.is_live_now,
url:xL({pause_on_navigation:U.pause_on_navigation,target:U.target||"new",value:U.url}),onClickCommand:null},Uq(P,f)}}else LeL(L.W,U);f=!0}}f&&(QY(L.player),L.HY())},CNc=function(L,W){var f=!1;
L.W||(L.W=ayA(L),g.C(L,L.W));for(var I=g.n(W.cards||[]),U=I.next();!U.done;U=I.next())U=U.value,U.cardRenderer&&(WeD(L.W,U.cardRenderer),f=!0);if(f){var e;(e=L.player.getVideoData())!=null&&g.UY(e)||(f=L.W,I=W.headerText?g.d3(W.headerText):"",g.My(f.R6,I),f.G&&(f.S.Z("player_tooltip_data_title_killswitch")?f.G.setAttribute("title",I):f.G.setAttribute("data-tooltip-title",I)),f.context.videoData.eventId&&(f.eventId=f.context.videoData.eventId),f.Yp=W.trackingParams?g.Zf(W.trackingParams):null,f.U=
W.closeButton.infoCardIconRenderer.trackingParams?g.Zf(W.closeButton.infoCardIconRenderer.trackingParams):null,f.Uv=W.icon.infoCardIconRenderer.trackingParams?g.Zf(W.icon.infoCardIconRenderer.trackingParams):null,L.HY());QY(L.player)}},GkX=function(L,W,f,I,U){if(!L.player.B().Ej){var e=[];
W.navigationEndpoint&&g.R(W.navigationEndpoint,g.l5)&&g.R(W.navigationEndpoint,g.l5).browseId&&e.push(new aJi("openUrl","click",new YRi("/channel/"+g.R(W.navigationEndpoint,g.l5).browseId,"new",!0,!0)));var b=W.watermark.thumbnails[0];I={channel_name:W.channelName,end_ms:W.endTimeMs,image_height:b.height,image_type:1,image_url:b.url,image_width:b.width,is_mobile:!1,session_data:{annotation_id:f,ei:U,feature:"iv",itct:W.trackingParams,src_vid:I},start_ms:W.startTimeMs};if(W.subscribeButton&&g.R(W.subscribeButton,
g.Os)){I.channel_id=g.R(W.subscribeButton,g.Os).channelId;var E;W=g.R(W.subscribeButton,g.Os);b=U=null;W.subscribed?(W.subscriberCountWithUnsubscribeText&&(U=g.d3(W.subscriberCountWithUnsubscribeText)),W.subscriberCountText&&(b=g.d3(W.subscriberCountText))):(W.subscriberCountText&&(U=g.d3(W.subscriberCountText)),W.subscriberCountWithSubscribeText&&(b=g.d3(W.subscriberCountWithSubscribeText)));var d,v=((d=g.R((E=W.signInEndpoint)==null?void 0:E.commandMetadata,g.Xw))==null?void 0:d.url)||"";E={subscribeText:g.d3(W.unsubscribedButtonText),
subscribeCount:U||"",unsubscribeText:g.d3(W.subscribedButtonText),unsubscribeCount:b||"",enabled:W.enabled||!1,classic:!1,subscribed:W.subscribed||!1,feature:"iv",signInUrl:v};I.standalone_subscribe_button_data=E}e=new NP5(f,"branding","branding",e,I);E=g6L(L);L.player.Z("web_player_overlay_positioned_layout")?(E.setAttribute("data-overlay-order","11"),L.player.tX(E,4,!0)):L.K.element.appendChild(E);e=new Eq(E,vX(L),e);e.QZ();g.C(e,e);L.J[f]=e}},J4t=function(L,W){return function(){var f=g.aR.apply(0,
arguments);
L.Je()||L.qV.push(g.YF.oQ(function(){W.apply(null,g.Aj(f))}))}},c4L=function(L){return L==="annotation-editor"||L==="live-dashboard"};
g.sY.prototype.j9=g.Uy(39,function(L,W){var f=g.a4(this.g1());f&&f.j9(L,W)});
var t3={},PO=null;g.BA(YL,g.oA);g.D=YL.prototype;g.D.getDuration=function(){return this.duration};
g.D.play=function(L){if(L||this.W==0)this.progress=0,this.coords=this.K;else if(this.isPlaying())return!1;J3(this);this.startTime=L=g.dt();this.isPaused()&&(this.startTime-=this.duration*this.progress);this.endTime=this.startTime+this.duration;this.T=this.startTime;this.progress||this.yp();this.H3("play");this.isPaused()&&this.H3("resume");this.W=1;var W=g.eL(this);W in t3||(t3[W]=this);vJn();rUc(this,L);return!0};
g.D.stop=function(L){J3(this);this.W=0;L&&(this.progress=1);BPc(this,this.progress);this.onStop();this.lc()};
g.D.pause=function(){this.isPlaying()&&(J3(this),this.W=-1,this.H3("pause"))};
g.D.w6=function(){this.W==0||this.stop(!1);this.H3("destroy");YL.q2.w6.call(this)};
g.D.destroy=function(){this.dispose()};
g.D.Bh=function(){this.H3("animate")};
g.D.H3=function(L){this.dispatchEvent(new AU5(L,this))};
g.BA(AU5,g.s0);g.BA(FX,YL);FX.prototype.N=function(){};
FX.prototype.Bh=function(){this.N();FX.q2.Bh.call(this)};
FX.prototype.lc=function(){this.N();FX.q2.lc.call(this)};
FX.prototype.yp=function(){this.N();FX.q2.yp.call(this)};
g.BA(SRQ,FX);SRQ.prototype.N=function(){this.element.style.left=Math.round(this.coords[0])+"px";this.element.style.top=Math.round(this.coords[1])+"px"};g.w(w4t,g.a);g.D=w4t.prototype;g.D.listen=function(L,W,f,I){f=(0,g.bc)(f,I||this.K);L=g.MT(L,W,f);this.W.push(L);return L};
g.D.Ay=function(L,W,f,I){f=(0,g.bc)(f,I||this.K);L=EJC(L,W,f);this.W.push(L);return L};
g.D.vT=function(L){g.n3(L);g.XO(this.W,L)};
g.D.removeAll=function(){g.n3(this.W);this.W.length=0};
g.D.w6=function(){this.removeAll();g.a.prototype.w6.call(this)};g.w(nJG,g.ux);g.D=nJG.prototype;g.D.load=function(){g.ux.prototype.load.call(this);if(!p6(this)){var L=g.Ogr(this.player.getVideoData());L?(L=MVO(L,X4A(this)),RN(this,L,!1)):VVO(this)}};
g.D.unload=function(){RN(this,null);this.T&&(this.T.abort(),this.T=null);g.ux.prototype.unload.call(this)};
g.D.RQ=function(L,W){return p6(this)?L==="loadCustomEndscreenRenderer"?(L=MVO(W,"new"),RN(this,L),!0):null:null};
g.D.getOptions=function(){return p6(this)?["loadCustomEndscreenRenderer"]:[]};
g.D.xC=function(){if(this.endscreen&&this.endscreen.elements){var L=this.player.getVideoContentRect();if(L&&L.width!==0&&L.height!==0){var W=this.player.getPlayerSize();if(W&&W.width!==0&&W.height!==0){var f=L.width/L.height;var I=0;for(var U=-1,e=0;e<sr5.length;e++){var b=Math.abs(W.width-sr5[e]);if(U===-1||I>=b)U=e,I=b}I=quW[U];this.N&&g.Ga(this.N.element,"outline-width",Math.max(W.width,W.height)+"px");for(W=0;W<this.endscreen.elements.length;++W)if(e=this.endscreen.elements[W].id,U=this.K[e],
b=this.J[e],U&&b){var E=b.width*f/b.aspectRatio,d=Math.round(b.width*L.width);e=Math.round(E*L.height);var v=L.left+Math.round(b.left*L.width),r=L.top+Math.round(b.top*L.height);g.Ls(U.element,d,e);g.kk(U.element,v,r);g.UF(U.element,iwc);d>256||e>256?g.$C(U.element,"ytp-ce-large-round"):d>96||e>96?g.$C(U.element,"ytp-ce-medium-round"):g.$C(U.element,"ytp-ce-small-round");g.UF(U.element,xNQ);d=b.left+b.width/2;b=b.top+E/2;g.$C(U.element,d<=.5&&b<=.5?"ytp-ce-top-left-quad":d>.5&&b<=.5?"ytp-ce-top-right-quad":
d<=.5&&b>.5?"ytp-ce-bottom-left-quad":"ytp-ce-bottom-right-quad");g.UF(U.element,quW);g.$C(U.element,I);(U=g.om(document,"div","ytp-ce-expanding-overlay-body",U.element)[0])&&g.Ga(U,"height",e+"px")}}}}};
g.D.onCueRangeEnter=function(L){if(this.endscreen)if(L.getId()==="ytp-ce-in-endscreen")sU(this,this.endscreen.impressionUrls),(L=g.z5())&&this.endscreen.visualElement&&g.ke(L,this.endscreen.visualElement),this.W&&(g.$C(this.W,"ytp-ce-element-show"),this.W.removeAttribute("aria-hidden"),this.player.MB()?g.$C(this.W,"ytp-ce-hide-button-lower"):g.IA(this.W,"ytp-ce-hide-button-lower"));else{L=L.getId().substring(15);var W=this.K[L],f=this.J[L];g.$C(W.element,"ytp-ce-element-show");W.element.removeAttribute("aria-hidden");
W=this.player.getRootNode();g.$C(W,"ytp-ce-shown");sU(this,f.impressionUrls);(W=g.z5())&&g.ke(W,f.visualElement);this.player.B().U&&this.player.xp("endscreenelementshown",L)}};
g.D.onCueRangeExit=function(L){if(L.getId()==="ytp-ce-in-endscreen")this.W&&(g.IA(this.W,"ytp-ce-element-show"),this.W.setAttribute("aria-hidden","true"));else{L=L.getId().substring(15);var W=this.K[L];g.IA(W.element,"ytp-ce-element-show");W.element.setAttribute("aria-hidden","true");W=this.player.getRootNode();g.IA(W,"ytp-ce-shown");this.player.B().U&&this.player.xp("endscreenelementhidden",L)}};
g.D.mw6=function(L){var W=this;L.target===window&&(new g.sn(function(){for(var f=g.n(Object.values(W.K)),I=f.next();!I.done;I=f.next())g.UF(I.value.element,["ytp-ce-force-expand","ytp-ce-element-hover","ytp-ce-element-shadow-show"])},0)).start()};
g.D.DE=function(L){for(var W=g.n(Object.values(this.K)),f=W.next();!f.done;f=W.next())f=f.value,L?f.element.setAttribute("hidden",""):f.element.removeAttribute("hidden")};
g.D.ZRa=function(L){this.W&&this.player.getRootNode().removeChild(this.W);L&&(g.$C(L,"ytp-ce-hide-button-container"),this.W=L,g.Ln(this.player,this.W,4))};
var sr5=[346,426,470,506,570,640,853,1280,1920],quW="ytp-ce-size-346 ytp-ce-size-426 ytp-ce-size-470 ytp-ce-size-506 ytp-ce-size-570 ytp-ce-size-640 ytp-ce-size-853 ytp-ce-size-1280 ytp-ce-size-1920".split(" "),xNQ=["ytp-ce-top-left-quad","ytp-ce-top-right-quad","ytp-ce-bottom-left-quad","ytp-ce-bottom-right-quad"],iwc=["ytp-ce-small-round","ytp-ce-medium-round","ytp-ce-large-round"];var FEA={D_H:"current",cV6:"new"};var CCC={CLOSE:"close",vRH:"openUrl",SUBSCRIBE:"subscribe"},p4G={gEH:"click",CLOSE:"close",rCw:"hidden",juw:"rollOut",tLa:"rollOver",Bpl:"shown"};NP5.prototype.vF=function(){var L=GAc(this,function(W){return W.type==="openUrl"&&W.url!=null});
return L?L.url:null};
var NHn={F31:"anchored",Jk:"branding",CHANNEL:"channel",A$V:"cta",Evh:"highlightText",jYU:"label",PLAYLIST:"playlist",POPUP:"popup",KIU:"speech",SUBSCRIBE:"subscribe",Gbe:"title",VIDEO:"video",UNP:"website"},Roc={Jk:"branding",RTP:"card",X26:"drawer",Laa:"highlight",UQV:"marker",xow:"promotion",TEXT:"text",H$P:"widget"};var Ken=[".iv-promo .iv-promo-contents .iv-promo-txt .iv-promo-link:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABQAAAAUBAMAAAB/pwA+AAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAHlBMVEVMaXH////////////////////////////////////Z6AnKAAAACXRSTlMA+/A2IuI1mJIldm0CAAAAAWJLR0QB/wIt3gAAAEVJREFUCNdjYGCYCQUMBJlACOIzIDElIcyZkwxgojOVWWDMSQauMKYySySUOSnBdSaUOZ0lEsac2YqwYiZ+JhwgM7E5HACgzVCI/YJ59AAAAABJRU5ErkJggg==) no-repeat center;background-size:10px;width:10px;height:10px}",
".iv-promo .iv-promo-actions .iv-promo-close:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAkAAAAJBAMAAAASvxsjAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJFBMVEVMaXH///////////////////////////////////////////9tKdXLAAAAC3RSTlMAVaQDpaimqQbl5rjXUFUAAAABYktHRAH/Ai3eAAAAPUlEQVQI12MQMmAwEmDwDmaOTmAw39663YCBuXp2MQMDQ+fOBgYG5ujVwQwMptvbgeLaxczVCQwiBgxmAgBkXg1FN5iwiAAAAABJRU5ErkJggg==) no-repeat center;background-size:9px;width:9px;height:9px}",
".iv-promo .iv-promo-actions .iv-promo-expand:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAQAAAAJBAMAAADnQZCTAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJFBMVEVMaXHMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMz////eMKB4AAAAC3RSTlMAOpE7k5Uvj5kpfRaQSaQAAAABYktHRAsf18TAAAAAHklEQVQI12MQYGBQZmBwTWCo0GSo6AKRQDZQRIABADXXA/UkIpvtAAAAAElFTkSuQmCC) no-repeat center;background-size:4px 9px;width:4px;height:9px}",".iv-promo-website-card-cta-redesign .iv-promo-round-expand-icon:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAADAAAAAwCAQAAAD9CzEMAAAAAmJLR0QA/4ePzL8AAAAJcEhZcwAACxMAAAsTAQCanBgAAAAHdElNRQfgCgUUEztsNfqrAAAAXklEQVRYw+3Uuw2AQAwEUUNXfBpDIvBRMhQwJJAScNrA0r4CdiQHjjAzK4NGKucPAFmCnZcmwcTphBNO9CTGH4VB+/Zm6YlYis9fhedXz38FNvFriCCl808iw8ysrBu65gCeuV/CfgAAAABJRU5ErkJggg==) no-repeat center;background-size:18px 18px;width:18px;height:18px}",
".iv-card-link-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABIAAAASBAMAAACk4JNkAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAGFBMVEVMaXG7u7u7u7u7u7u7u7u7u7u7u7v///+WKTAlAAAABnRSTlMAFdQWbGj9GiOuAAAAAWJLR0QHFmGI6wAAAEhJREFUCNdjYACBNCBgQGMxMKrBWEJJaRAJRjVlKEsoSQDIAqtSZICwgEIQFkgIZBRECMxiBqsCsVjAqsCygQwwFgMeFgQgswBg2xjLrfC4mgAAAABJRU5ErkJggg==) no-repeat center;background-size:9px;width:9px;height:9px}",".iv-card-playlist-video-count:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABgAAAAYBAMAAAASWSDLAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJFBMVEVMaXH///////////////////////////////////////////9tKdXLAAAAC3RSTlMAvDeyLvxYtDK9Ogx4T1QAAAABYktHRAH/Ai3eAAAAK0lEQVQY02NgoBjshgO8HJoYwKiAMGAD92YHJM7uMCTO9gaEHs4FlPuZAQC8Fj8x/xHjxwAAAABJRU5ErkJggg==) no-repeat center;background-size:24px;width:24px;height:24px}"],
THD=[".iv-drawer-close-button:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAwAAAAMAgMAAAArG7R0AAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAACVBMVEVMaXH////////OZTV/AAAAAnRSTlMAoKBFbtAAAAABYktHRAH/Ai3eAAAAKUlEQVQI12MIYGBlSGGQBMIUBjbHCQyM0xwYGDIZwBjEBomB5EBqgGoBolQGzYuy51cAAAAASUVORK5CYII=) no-repeat center;background-size:12px;width:12px;height:12px}",".iv-ad-info-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAsAAAALCAMAAACecocUAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAVFBMVEVMaXGUlJSYmJiZmZmYmJiXl5eZmZmZmZmWlpaVlZWOjo6ZmZmSkpKXl5eYmJiYmJiZmZmZmZmZmZmZmZmYmJiJiYmXl5eZmZmYmJiWlpaZmZn///+81lbeAAAAGnRSTlMAE5DM80DliTMMEjccWIM5p1UjaTQNgB5cLlr5mgUAAAABYktHRBsCYNSkAAAAVElEQVQI102NRw7AIBADhw7ppIf/PzQLJ/ZgWSNrFlDaWKMVcs6HmGLwTqjEME6CFDrAXBYIGhNh3TJEg02wHydctvFc7sbrvnXZV8/zfs3T+7u/P7CrAso35YfPAAAAAElFTkSuQmCC) no-repeat center;background-size:11px;width:11px;height:11px}",
".annotation-close-button {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQBAMAAADt3eJSAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAALVBMVEVMaXEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA/Pz9aWloBAQGZmZlbW1v///+X9wUzAAAACHRSTlMANprf+g6lyRmB9hUAAAABYktHRA5vvTBPAAAAWUlEQVQI12NgYBAycVZkAIKwDiBIZWBgrQAx2gMY2DrAIIFBomPWju6VHY0MGh1rbu891dHEYNGx9+yd2x3NDB4d3XfO7uhoQTDgUnDFcO1wA+FWwC2FOQMAdKg6tUSAFEAAAAAASUVORK5CYII=) no-repeat center}",".annotation-link-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAACIAAAAiCAMAAAANmfvwAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAUVBMVEVMaXH////////////////////////////////////////////////////////////////////////////////////////////////////////JzkR1AAAAGnRSTlMAfXf+c3xsdGdv/GJoXPtXXflSVk5L7DBH9VeFfsQAAAABYktHRAH/Ai3eAAAAgElEQVQ4y93SSQ6AIAwFULSOOOJs739Qf9SF0VA2uNCu+psHaQJK7cVCqY+Rg92PXA++Q84KnCR03UIRJrFEKMEgZYFQhpyzQHSBWJJAdIVUENtJ3SC0mu3EdOh7zXZiBrRdzQLJ0Y1GfOlpVstD3HaZktX9X/gvRCxvxL6FR7IBS1RTM5xIpLoAAAAASUVORK5CYII=) no-repeat center}"];g.w(OU,g.a);g.D=OU.prototype;g.D.addCueRange=function(L,W,f,I,U){L=new g.sW(L,W,{id:f,namespace:"annotations_module"});I&&this.oh.set(L,I);U&&this.Cl.set(L,U);this.context.S.AD([L],1)};
g.D.QZ=function(){this.context.K.subscribe("resize",this.FT,this)};
g.D.Mk=function(){return this.element};
g.D.CT=function(L,W,f,I,U,e){if(this.m2)return!1;e&&(e.stopPropagation(),e.preventDefault());this.navigate(L,f,I,U);return!1};
g.D.show=function(){};
g.D.hide=function(){};
g.D.destroy=function(){g.wy(this.Mk())};
g.D.FT=function(){};
g.D.navigate=function(L,W,f,I){var U=this,e=iX(L);if(e){var b=HrW(e,L.target),E=function(){L.W&&U.context.S.pauseVideo();var d=U.context.videoData.ly||!1,v=g.WR(e||"");d&&v&&(v.v||v.list)?U.context.S.lK(v.v,W,v.list,!1):g.R7(e||"",b==="current"?"_top":void 0,W)};
b==="new"&&(E(),E=null);d9(this.context.logger,f,E,I);kAt(e)||(f=g.z5(),I=W.itct,f&&I&&g.OO(f,g.Zf(I)))}};
g.D.w6=function(){this.oh.clear();this.Cl.clear();g.a.prototype.w6.call(this)};
g.D.createElement=function(L){L=new g.G(L);g.C(this,L);return L.element};g.w(Orc,OU);g.D=Orc.prototype;g.D.HC=function(){this.qV&&Uq(this,this.qV)};
g.D.isAvailable=function(){var L;if(L=!!this.cards.length)(L=this.S.getRootNode())?(L=g.Wb(L),L=173<L.width&&173<L.height):L=!1;return L};
g.D.FT=function(){var L=this.isAvailable();g.$V(this.Mk(),L);g.e2(this.context.S.getRootNode(),g.nH.IV_DRAWER_ENABLED,L);QY(this.S)};
g.D.destroy=function(){this.S.j9(!1);try{this.S.getRootNode().removeChild(this.T)}catch(L){}g.LT(this.Kl);g.T4(this.Hd);this.Vs&&this.Vs.dispose();this.J&&this.J.dispose();OU.prototype.destroy.call(this)};
g.D.zj=function(){var L=this;this.context.W.listen(g.bd("iv-drawer-close-button",this.T),"click",this.N0,this);this.context.W.listen(this.K,"touchend",function(){L.ys.start()});
this.context.W.listen(this.K,"scroll",this.Qr,this);this.context.K.subscribe("onHideControls",function(){L.g6=!0});
this.context.K.subscribe("onShowControls",function(){L.g6=!1});
this.context.K.subscribe("onVideoAreaChange",function(){L.g6=g.Wj(L.S.getRootNode(),"ytp-autohide")});
this.Kl.push(g.OE("iv-button-shown",this.JeU,this));this.Kl.push(g.OE("iv-button-hidden",this.vps,this));eoD(this)};
g.D.findLastIndex=function(L){if(this.cards.length===0)return 0;var W=g.zv(this.cards,function(f){return L.bX.startMs>f.bX.startMs||L.bX.startMs===f.bX.startMs&&L.bX.timestamp>=f.bX.timestamp?!0:!1});
return W===-1?0:W+1};
g.D.N0=function(){if(this.N){d9(this.context.logger,bg(this).OS.close);var L=g.z5();L&&this.U&&g.OO(L,this.U);ff(this)}};
g.D.Qr=function(){g.e2(this.T,"iv-drawer-scrolled",this.K.scrollTop>0)};
g.D.JeU=function(){var L=g.z5(),W=bg(this);W=W?W.Uv:this.Uv;L&&W&&g.Hd(L,[W])};
g.D.vps=function(){var L=g.z5(),W=bg(this);W=W?W.Uv:this.Uv;L&&W&&g.lA(L,[W])};
g.D.lY=function(){var L=bg(this);d9(this.context.logger,L.OS.zX);var W=g.z5();if(W&&L)if(this.S.Z("web_infocards_teaser_show_logging_fix")){var f=[];L.qB&&f.push(L.qB);L.Uv&&f.push(L.Uv);f.length>0&&g.Hd(W,f)}else g.Hd(W,[L.qB,L.Uv])};
g.D.Hlh=function(){var L=g.z5(),W=bg(this);L&&W&&g.lA(L,[W.qB])};
g.D.wq=function(L){var W=bg(this),f=g.z5();this.W?L?(L=this.context.logger,d9(L,W.OS.GT),L.S.sendVideoStatsEngageEvent(4,void 0),f&&W.qB&&g.OO(f,W.qB)):(L=this.context.logger,d9(L,W.OS.GT),L.S.sendVideoStatsEngageEvent(4,void 0),f&&W.Uv&&g.OO(f,W.Uv)):(L=this.context.logger,d9(L,W.OS.GT),L.S.sendVideoStatsEngageEvent(4,void 0),f&&this.Uv&&g.OO(f,this.Uv))};g.w(hQ,OU);hQ.prototype.QZ=function(){OU.prototype.QZ.call(this);r45(this)};
hQ.prototype.show=function(){OU.prototype.show.call(this);var L=g.z5(),W=this.annotation.data;L&&W&&(W=W.session_data)&&g.Hd(L,[g.Zf(W.itct)])};
hQ.prototype.hide=function(){OU.prototype.hide.call(this);var L=g.z5(),W=this.annotation.data;L&&W&&(W=W.session_data)&&g.lA(L,[g.Zf(W.itct)])};g.w(Eq,hQ);
Eq.prototype.show=function(){if(!this.isActive){hQ.prototype.show.call(this);if(!this.V){g.$C(this.Mk(),"iv-branding");var L=this.annotation.data;this.K=this.createElement({Y:"img",d6:["branding-img","iv-click-target"],L:{"aria-label":"\ucc44\ub110 \uc6cc\ud130\ub9c8\ud06c",src:L.image_url,width:L.image_width,height:L.image_height}});g.$V(this.K,!1);var W=this.createElement({Y:"button",d6:["branding-img-container","ytp-button"]});W.appendChild(this.K);this.Mk().appendChild(W);var f=this.annotation.vF();f&&
Lf(this,W,f,this.annotation.id,L.session_data);this.context.S.Z("disable_branding_context")||Zwv(this,L);this.V=!0}g.$V(this.Mk(),!0);this.isActive=!0;if(this.K){try{BHO(this,this.K)}catch(I){}g.$C(this.context.S.getRootNode(),"ytp-branding-shown");this.context.S.getRootNode().style.setProperty("--branding-image-width",this.K.getAttribute("width")+"px")}}};
Eq.prototype.hide=function(){this.isActive&&(hQ.prototype.hide.call(this),g.$V(this.Mk(),!1),this.isActive=!1,g.IA(this.context.S.getRootNode(),"ytp-branding-shown"))};
Eq.prototype.destroy=function(){this.W&&(this.W.dispose(),this.W=null);g.IA(this.context.S.getRootNode(),"ytp-branding-shown");hQ.prototype.destroy.call(this)};g.w(w8n,hQ);g.D=w8n.prototype;g.D.show=function(){this.isActive||(hQ.prototype.show.call(this),this.X||(MoC(this),this.X=!0),g.$V(this.Mk(),!0),g.Fm(function(){g.IA(this.Mk(),"iv-promo-inactive")},100,this),this.Mk().removeAttribute("aria-hidden"),this.isActive=!0,mNt(this),n6O(this),X85(this,this.J))};
g.D.hide=function(){this.isActive&&(g.$C(this.Mk(),"iv-promo-inactive"),this.isActive=!1,this.Mk().setAttribute("aria-hidden","true"))};
g.D.CT=function(L,W,f,I,U,e){return this.isCollapsed?!1:hQ.prototype.CT.call(this,L,W,f,I,U,e)};
g.D.dI=function(L){this.U=!0;zoL(this,500,L)};
g.D.Mh=function(){this.U=!1;Voc(this)};
g.D.PG=function(L){L.stopPropagation();this.hide()};
g.D.YW=function(L){L.stopPropagation();mNt(this);this.isCollapsed=!0;g.$C(this.Mk(),"iv-promo-collapsed-no-delay");this.G.start()};
g.D.destroy=function(){this.G.dispose();hQ.prototype.destroy.call(this)};g.w(y45,g.ux);g.D=y45.prototype;g.D.RQ=function(L,W){if(!c4L(this.player.B().playerStyle))return null;switch(L){case "loadCustomAnnotationsXml":return(L=g.lH(W))&&PNL(this,L),!0;case "removeCustomAnnotationById":return W&&this.W&&(fyL(this.W,W),QY(this.player)),!0}return null};
g.D.getOptions=function(){return c4L(this.player.B().playerStyle)?["loadCustomAnnotationsXml","removeCustomAnnotationById"]:[]};
g.D.UN=function(){var L=this.player.B(),W=this.player.getVideoData(),f=L.annotationsLoadPolicy||W.annotationsLoadPolicy;return W.ly||this.player.isMutedByEmbedsMutedAutoplay()?!1:f===1&&!W.xm||L.g6.get(W.videoId)||g.e4(W)||g.oa(W)?!0:!1};
g.D.HY=function(){if(this.N){var L=this.player.kC().getVideoContentRect(!0);g.Ls(this.N.element,L.width,L.height);g.kk(this.N.element,L.left,L.top)}if(this.W){var W=this.player.J7();L=this.W;W=W.width;g.e2(L.T,"iv-drawer-small",W<=426);g.e2(L.T,"iv-drawer-big",W>=1280)}};
g.D.uY=function(L){QrO(this,L.state);g.x(L.state,2)&&(this.MB()&&this.Jx()&&this.player.getPresentingPlayerType()!==2&&this.tb(!1),this.j9(!1))};
g.D.load=function(){function L(b){var E=W.loadNumber;W.G=null;W.loaded&&W.loadNumber===E&&W.player.getVideoData().videoId===I&&(b=g.vR(b)&&b.responseXML?b.responseXML:null)&&(PNL(W,b),g.$C(W.player.getRootNode(),"iv-module-loaded"))}
var W=this;g.ux.prototype.load.call(this);QrO(this,this.player.getPlayerStateObject());this.loadNumber++;var f=this.player.getVideoData(),I=f.videoId;g.H3()&&(L=J4t(this,L));var U={format:"XML",onFinish:L,onError:function(){W.G=null},
urlParams:{}};f.isPharma&&(U.urlParams.pharma="1");U.method="POST";U.withCredentials=!0;var e=this.player.B().g6.get(I);e&&YuO(U,e);e=e&&(e.Yg||e.ao);if(!f.uP||e)f.Hd?jr5(this,f.Hd,U):(this.V=function(){if(!W.U)W.onVideoDataChange(U);var b=W.player.getVideoData();(b==null?0:g.UY(b))&&!W.Kl&&p8i(W,b)},this.player.addEventListener("videodatachange",this.V));
g.Ln(this.player,this.N.element,4);this.HY();(e=g.e4(f))&&CNc(this,e);(e=g.oa(f))&&e.featuredChannel&&GkX(this,e.featuredChannel,e.annotationId||"branding",f.videoId||null,f.eventId||null);this.rW=g.bd("ytp-cards-button",this.player.getRootNode());g.UY(f)&&p8i(this,f)};
g.D.onVideoDataChange=function(L){var W=this.player.getVideoData();W.Hd&&jr5(this,W.Hd,L)};
g.D.unload=function(){this.player.V2("annotations_module");for(var L=g.n(Object.keys(this.J)),W=L.next();!W.done;W=L.next())this.J[W.value].destroy();this.X=null;this.W&&(this.W.destroy(),this.W=null,QY(this.player));this.U=!1;this.G&&(this.G.abort(),this.G=null);this.Kl=!1;this.J={};this.K.hide();g.ux.prototype.unload.call(this);this.N.detach();this.V&&(this.player.removeEventListener("videodatachange",this.V),this.V=null)};
g.D.FD=function(L){L===this.player.getVideoData().videoId&&(this.loaded?Fec(this):this.load())};
g.D.MB=function(){var L;return((L=this.W)==null?void 0:L.isAvailable())||this.Kl};
g.D.Jx=function(){return!!this.W&&this.W.N};
g.D.tb=function(L,W,f){W=W===void 0?!1:W;this.MB();this.W&&(L?f?$U(this.W,f,W):$U(this.W,"YOUTUBE_DRAWER_AUTO_OPEN",W):ff(this.W))};
g.D.j9=function(L,W){this.player.publish(L?"cardsteasershow":"cardsteaserhide",W)};
g.D.w6=function(){this.player.B().g6.unsubscribe("vast_info_card_add",this.FD,this);g.IA(this.player.getRootNode(),g.nH.IV_DRAWER_OPEN);for(var L=this.qV,W=g.YF,f=0,I=L.length;f<I;f++)W.iE(L[f]);this.qV.length=0;g.ux.prototype.w6.call(this)};
g.D.createElement=function(L){L=new g.G(L);g.C(this,L);return L.element};g.mD("annotations_module",y45);g.mD("creatorendscreen",nJG);})(_yt_player);
